# Generated by Django 3.1.1 on 2020-09-27 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flight_fighter_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticatedPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
