# Generated by Django 3.1.1 on 2020-09-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_fighter_api', '0003_auto_20200927_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
