# Generated by Django 3.1.1 on 2020-09-27 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_fighter_api', '0004_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(64)]),
        ),
    ]
