# Generated by Django 3.1.1 on 2020-09-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_fighter_api', '0005_game_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authplayer',
            name='token',
            field=models.CharField(max_length=96),
        ),
    ]
