# Generated by Django 3.1.1 on 2020-10-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_fighter_api', '0007_auto_20200927_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='token',
            field=models.CharField(default='', max_length=96, null=True),
        ),
    ]
