# Generated by Django 3.1.2 on 2020-10-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_race_api', '0008_auto_20201001_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='x_position',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='y_position',
            field=models.FloatField(null=True),
        ),
    ]
